# Alternative oss boxes: https://app.vagrantup.com/bento

Vagrant.configure('2') do |config|
  config.vm.define 'ronny01'
  #
  # Run Ansible from the Vagrant Host
  #
  config.vm.network 'forwarded_port', guest: 8000, host: 1234

  config.vm.box = 'bento/debian-10.11'
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'playbook.yml'
    ansible.groups = {
      'station' => ['ronny01']
    }
    # https://github.com/hashicorp/vagrant/issues/9893
    # ansible.raw_arguments = ['--inventory', 'inventory' ]
    # ansible.verbose = 'vvv'
  end
end
